# Generated by Django 3.1.2 on 2020-11-27 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menulist', '0003_menu_takeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='アレルギー名')),
            ],
            options={
                'db_table': 'allergy',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='allergy',
            field=models.ManyToManyField(to='menulist.Allergy', verbose_name='含むアレルギー'),
        ),
    ]
